/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KonamiListener {
    }
}
declare global {
    interface HTMLKonamiListenerElement extends Components.KonamiListener, HTMLStencilElement {
    }
    var HTMLKonamiListenerElement: {
        prototype: HTMLKonamiListenerElement;
        new (): HTMLKonamiListenerElement;
    };
    interface HTMLElementTagNameMap {
        "konami-listener": HTMLKonamiListenerElement;
    }
}
declare namespace LocalJSX {
    interface KonamiListener {
        "onInput"?: (event: CustomEvent<any>) => void;
        "onMatch"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "konami-listener": KonamiListener;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "konami-listener": LocalJSX.KonamiListener & JSXBase.HTMLAttributes<HTMLKonamiListenerElement>;
        }
    }
}
